import type { Metadata } from "next";
import "@/styles/globals.css";
import "@/index.css";
import { AppProvider } from "@/lib/AppContext";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
    title: "Responsive Web Application",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <link rel="icon" href="/assets/ZeroWaste-icon.svg" type="image/svg+xml" />
            </head>
            <body suppressHydrationWarning>
                <AppProvider>
                    {children}
                    <Toaster />
                </AppProvider>
            </body>
        </html>
    );
}
